<?php

use common\grid\EnumColumn;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\search\ArticleSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('backend', 'Security');
$this->params['breadcrumbs'][] = $this->title;
$items = [1=>'On',0=>'Off'];
?>

<div class="row security-page">
    <div class="col-md-8 col-xs-12">
        <div class="panel panel-filled">
            <div class="panel-body">
                <h3 class="m-t-md">
                    Account Security
                </h3>
                
                <?php $form = ActiveForm::begin(); ?>
                
                <?php echo $form->field($model, 'has2fa',[
                    'labelOptions' => ['class' => 'col-sm-3 control-label'],
                    'template'=> "{label}<div class='col-sm-9 input-group'>{input}</div>\n{hint}\n{error}"
                    ])->radioList($items,['id'=>'input-has2fa']) ?>
                <?php echo $form->field($model, 'one_time_password',[
                    'labelOptions' => ['class' => 'col-sm-3 control-label'],
                    'template'=> "{label}<div class='col-sm-9 input-group input-group-lg'><span class='input-group-addon'><i class='fa fa-qrcode fa-lg'></i></span>{input}</div>\n{hint}\n{error}"
                    ])
                    ->textInput(['maxlength' => 6]) ?>
                    
                <div id="extra-2fa" style="<?php $model->has2fa? : 'display:none' ?>">
                <?php echo $form->field($model, 'twofa_ex_create_order',[
                    'labelOptions' => ['class' => 'col-sm-3 control-label'],
                    'template'=> "{label}<div class='col-sm-9 input-group'>{input}</div>\n{hint}\n{error}"
                    ])->radioList($items) ?>
                <?php echo $form->field($model, 'twofa_ex_cancel_order',[
                    'labelOptions' => ['class' => 'col-sm-3 control-label'],
                    'template'=> "{label}<div class='col-sm-9 input-group'>{input}</div>\n{hint}\n{error}"
                    ])->radioList($items) ?>
                <?php echo $form->field($model, 'twofa_lending',[
                    'labelOptions' => ['class' => 'col-sm-3 control-label'],
                    'template'=> "{label}<div class='col-sm-9 input-group'>{input}</div>\n{hint}\n{error}"
                    ])->radioList($items) ?>
                <?php echo $form->field($model, 'twofa_withdraw',[
                    'labelOptions' => ['class' => 'col-sm-3 control-label'],
                    'template'=> "{label}<div class='col-sm-9 input-group'>{input}</div>\n{hint}\n{error}"
                    ])->radioList($items) ?>
                </div>
                
                <div class="form-group">
                    <div class="col-sm-3 text-right">
                        <?php echo Html::submitButton(Yii::t('backend', 'Submit'),['class' =>'btn btn-primary']) ?>
                    </div>
                    <div class="col-sm-9 text-left">
                        <?php echo Html::button(Yii::t('backend', 'Cancel'),['class' =>'btn btn-default']) ?>    
                    </div>
                </div>
                
                <?php ActiveForm::end(); ?>
            </div>
        </div>
    </div>


</div>


<div class="row">
<div class="col-md-6">
    <div class="panel panel-filled">
        <div class="panel-body">
            <h3 class="m-t-md">
                Account Security
            </h3>
            
            <p>To setup two factor authentication you first need to download Google Authenticator:</p>
            <p><i class="fa fa-android"></i>  <a href="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2" target="_blank" class="text-black">Google Authenticator for Android (Play Store)</a></p>
            <p><i class="fa fa-apple"></i>  <a href="https://itunes.apple.com/en/app/google-authenticator/id388497605?mt=8" target="_blank" class="text-black">Google Authenticator for iOS (Apple App Store)</a></p>
            <p>Then scan the the barcode or, if you are not able to scan the barcode, you can enter the "Security Key" manually.</p>
                     
            <p>Enter the 6 digit code generated by Google Authenticator in the 2FA Code box and switch "Enable Two-Factor" to On</p>
            <p><span class="label label-danger">Important</span> Save this secret code for future reference</p>
            <p><em>Note: No Google account is required to use Google Authenticator; skip any Google logins</em></p>
        </div>
    </div>
</div>
<div class="col-md-6">
    <div class="panel panel-filled">
        <div class="panel-body">
            <h3 class="m-t-md">
            Security Key:</h3> 
            <center>
                <h3><span style="font-family:Courier;color:#FF4508;letter-spacing:2px;font-size:22px;">
                    <?php echo $secret ?>
                    </span></h3>
            </center>
            <center>
                <small class="text-black"><em>(Time Based Code)</em></small>
            </center>
            <br/>
            <center>
                <img src="<?= $code ?>" />
            </center>   
         </div>
    </div>            
</div>
</div>
